# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_auther', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_title', models.CharField(max_length=100)),
                ('C_descrbtion', models.TextField(max_length=1000)),
                ('C_pupdate', models.DateTimeField(auto_now_add=True)),
                ('C_location', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Cource')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L_title', models.CharField(max_length=100)),
                ('L_sorces', models.TextField(max_length=500)),
                ('L_objectives', models.TextField(max_length=500)),
                ('L_pupdate', models.DateTimeField(auto_now_add=True)),
                ('L_link', models.URLField()),
                ('Cources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Cource')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_name', models.CharField(max_length=100)),
                ('S_code', models.CharField(max_length=7)),
                ('S_collage', models.CharField(max_length=100)),
                ('S_level', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Lecture')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='Lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Lecture'),
        ),
        migrations.AddField(
            model_name='cource',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Subject'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Cource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Cource'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Lecture'),
        ),
    ]
